// eslint-disable-next-line
export const profileActionTypes = {
  GET_PROFILE_START: 'GET_PROFILE_START',
  GET_PROFILE_SUCCESS: 'GET_PROFILE_SUCESS',
  GET_PROFILE_FAILURE: 'GET_PROFILE_FAILURE',
  SET_USER_PROFILE: 'SET_USER_PROFILE',
  SET_MODAL_VISIBLE: 'SET_MODAL_VISIBLE',
  EMPTY_UP_PROFILE: 'EMPTY_UP_PROFILE',
  UPLOAD_IMAGE_START: 'UPUPLOAD_IMAGE_START',
  UPLOAD_IMAGE_SUCCESS: 'UPLOAD_IMAGE_SUCCESS',
  UPLOAD_IMAGE_FAILURE: 'UPLOAD_IMAGE_FAILURE',
  EDIT_PROFILE_START: 'EDIT_PROFILE_START',
  EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
  EDIT_PROFILE_FAILURE: 'EDIT_PROFILE_FAILURE',
};
